### ISSUE TITLE
MISSING THREADED FACTORY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by ghost** [PocketMinePlusPlus/PocketMinePlusPlus#25]

**Comment by Encritary** [comment]
?

**Comment by ghost** [comment]
Um... It needs the threaded factory file to boot up.

**Comment by ghost** [comment]
In the spl file, the "Threaded Factory" is missing.

**Comment by Encritary** [comment]
@Lucario2 use https://github.com/PrismarineMC/Prismarine instead, PocketMinePlusPlus is abandoded.
