### ISSUE TITLE
Copy-paste

### ISSUE THREAD

**Issue by ghost** [PocketMinePlusPlus/PocketMinePlusPlus#26]
Someone parts of code copy-pasted from my project 
https://github.com/Zzm317/MyZombie
https://github.com/Zzm317/MyOwnWorld
Implementation of AI for mobs is very similar to mine. 
How can you explain this?

**Comment by Encritary** [comment]
It is temporary, our other developer already writes AI for mobs. Don't worry :)

**Comment by ghost** [comment]
https://github.com/iTXTech/Genisys/issues/55
so what do this mean?
